"""Type stubs for the pytheia.io module."""
from typing import Dict, List, Optional, Tuple, Union, Any
import numpy as np
from numpy.typing import NDArray

# This module likely contains IO functions for reading/writing reconstruction data
# Based on the convert_sift_key_file.cc, this might include:

def ReadSiftKeyTextFile(filepath: str) -> Tuple[List[NDArray], List[Any]]: ...
def WriteSiftKeyBinaryFile(filepath: str, descriptors: List[NDArray], keypoints: List[Any]) -> bool: ...

# Other potential IO functions
def ReadReconstruction(filepath: str) -> Any: ...
def WriteReconstruction(reconstruction: Any, filepath: str) -> bool: ...
def ReadCamerasAndImages(filepath: str) -> Tuple[Dict[int, Any], Dict[int, Any]]: ...
def WriteCamerasAndImages(cameras: Dict[int, Any], images: Dict[int, Any], filepath: str) -> bool: ...