"""Type stubs for the pytheia.math module."""
from typing import List, Optional, Tuple, Dict, Any, Union
import numpy as np
from numpy.typing import NDArray

def FindQuadraticPolynomialRoots(a: float, b: float, c: float) -> List[complex]: ...

# Rotation functions
def AlignRotations(rotations: List[NDArray], gt_rotations: List[NDArray]) -> NDArray: ...
def AlignOrientations(orientations_dict: Dict[int, NDArray]) -> NDArray: ...
def MultiplyRotations(R1: NDArray, R2: NDArray) -> NDArray: ...
def RelativeRotationFromTwoRotations(rotation1: NDArray, rotation2: NDArray) -> NDArray: ...
def ApplyRelativeRotation(rotation1: NDArray, relative_rotation: NDArray) -> NDArray: ...
def RelativeTranslationFromTwoPositions(position1: NDArray, position2: NDArray, rotation1: NDArray) -> NDArray: ...