from __future__ import annotations
__all__: list[str] = ['BundlerCamera', 'BundlerFileReader', 'BundlerObservation', 'BundlerPoint', 'ImportNVMFile', 'ListImgEntry', 'PopulateImageSizesAndPrincipalPoints', 'Read1DSFM', 'ReadBundlerFiles', 'ReadReconstruction', 'ReadStrechaDataset', 'WriteBundlerFiles', 'WriteColmapFiles', 'WriteNVMFile', 'WriteNerfStudio', 'WritePlyFile', 'WriteReconstruction', 'WriteReconstructionJson', 'WriteSdfStudio']
class BundlerCamera:
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @property
    def focal_length(*args, **kwargs):
        ...
    @focal_length.setter
    def focal_length(*args, **kwargs):
        ...
    @property
    def radial_coeff_1(*args, **kwargs):
        ...
    @radial_coeff_1.setter
    def radial_coeff_1(*args, **kwargs):
        ...
    @property
    def radial_coeff_2(*args, **kwargs):
        ...
    @radial_coeff_2.setter
    def radial_coeff_2(*args, **kwargs):
        ...
    @property
    def rotation(*args, **kwargs):
        ...
    @rotation.setter
    def rotation(*args, **kwargs):
        ...
    @property
    def translation(*args, **kwargs):
        ...
    @translation.setter
    def translation(*args, **kwargs):
        ...
class BundlerFileReader:
    @staticmethod
    def ParseBundleFile(*args, **kwargs):
        ...
    @staticmethod
    def ParseListsFile(*args, **kwargs):
        ...
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @staticmethod
    def cameras(*args, **kwargs):
        ...
    @staticmethod
    def img_entries(*args, **kwargs):
        ...
    @staticmethod
    def points(*args, **kwargs):
        ...
class BundlerObservation:
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @property
    def camera_index(*args, **kwargs):
        ...
    @camera_index.setter
    def camera_index(*args, **kwargs):
        ...
    @property
    def feature_index(*args, **kwargs):
        ...
    @feature_index.setter
    def feature_index(*args, **kwargs):
        ...
    @property
    def x(*args, **kwargs):
        ...
    @x.setter
    def x(*args, **kwargs):
        ...
    @property
    def y(*args, **kwargs):
        ...
    @y.setter
    def y(*args, **kwargs):
        ...
class BundlerPoint:
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @property
    def color(*args, **kwargs):
        ...
    @color.setter
    def color(*args, **kwargs):
        ...
    @property
    def position(*args, **kwargs):
        ...
    @position.setter
    def position(*args, **kwargs):
        ...
    @property
    def view_list(*args, **kwargs):
        ...
    @view_list.setter
    def view_list(*args, **kwargs):
        ...
class ListImgEntry:
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @property
    def filename(*args, **kwargs):
        ...
    @filename.setter
    def filename(*args, **kwargs):
        ...
    @property
    def focal_length(*args, **kwargs):
        ...
    @focal_length.setter
    def focal_length(*args, **kwargs):
        ...
    @property
    def second_entry(*args, **kwargs):
        ...
    @second_entry.setter
    def second_entry(*args, **kwargs):
        ...
def ImportNVMFile(*args, **kwargs):
    ...
def PopulateImageSizesAndPrincipalPoints(*args, **kwargs):
    ...
def Read1DSFM(*args, **kwargs):
    ...
def ReadBundlerFiles(*args, **kwargs):
    ...
def ReadReconstruction(*args, **kwargs):
    ...
def ReadStrechaDataset(*args, **kwargs):
    ...
def WriteBundlerFiles(*args, **kwargs):
    ...
def WriteColmapFiles(*args, **kwargs):
    ...
def WriteNVMFile(*args, **kwargs):
    ...
def WriteNerfStudio(*args, **kwargs):
    ...
def WritePlyFile(*args, **kwargs):
    ...
def WriteReconstruction(*args, **kwargs):
    ...
def WriteReconstructionJson(*args, **kwargs):
    ...
def WriteSdfStudio(*args, **kwargs):
    ...
