from __future__ import annotations
import collections.abc
import typing
import numpy
import numpy.typing

__all__: list[str] = [
    'BundlerCamera',
    'BundlerFileReader',
    'BundlerObservation',
    'BundlerPoint',
    'ImportNVMFile',
    'ListImgEntry',
    'PopulateImageSizesAndPrincipalPoints',
    'Read1DSFM',
    'ReadBundlerFiles',
    'ReadReconstruction',
    'ReadStrechaDataset',
    'WriteBundlerFiles',
    'WriteColmapFiles',
    'WriteNVMFile',
    'WriteNerfStudio',
    'WritePlyFile',
    'WriteReconstruction',
    'WriteReconstructionJson',
    'WriteSdfStudio',
]

class BundlerObservation:
    def __init__(self) -> None:
        ...
    @property
    def camera_index(self) -> int:
        ...
    @camera_index.setter
    def camera_index(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def feature_index(self) -> int:
        ...
    @feature_index.setter
    def feature_index(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def x(self) -> int:
        ...
    @x.setter
    def x(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def y(self) -> int:
        ...
    @y.setter
    def y(self, arg0: typing.SupportsInt) -> None:
        ...

class BundlerPoint:
    def __init__(self) -> None:
        ...
    @property
    def color(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @color.setter
    def color(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def view_list(self) -> list[BundlerObservation]:
        ...
    @view_list.setter
    def view_list(self, arg0: collections.abc.Sequence[BundlerObservation]) -> None:
        ...

class BundlerCamera:
    def __init__(self) -> None:
        ...
    @property
    def focal_length(self) -> float:
        ...
    @focal_length.setter
    def focal_length(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def radial_coeff_1(self) -> float:
        ...
    @radial_coeff_1.setter
    def radial_coeff_1(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def radial_coeff_2(self) -> float:
        ...
    @radial_coeff_2.setter
    def radial_coeff_2(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @rotation.setter
    def rotation(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def translation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @translation.setter
    def translation(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...

class BundlerFileReader:
    def ParseBundleFile(self) -> bool:
        ...
    def ParseListsFile(self) -> bool:
        ...
    def __init__(self, arg0: str, arg1: str) -> None:
        ...
    def cameras(self) -> list[BundlerCamera]:
        ...
    def img_entries(self) -> list[ListImgEntry]:
        ...
    def points(self) -> list[BundlerPoint]:
        ...

class ListImgEntry:
    filename: str
    def __init__(self) -> None:
        ...
    @property
    def focal_length(self) -> float:
        ...
    @focal_length.setter
    def focal_length(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def second_entry(self) -> float:
        ...
    @second_entry.setter
    def second_entry(self, arg0: typing.SupportsFloat) -> None:
        ...

def ImportNVMFile(arg0: str) -> tuple[bool, ...]:
    ...
def PopulateImageSizesAndPrincipalPoints(arg0: str) -> tuple[bool, ...]:
    ...
def Read1DSFM(arg0: str) -> tuple[bool, ..., ...]:
    ...
def ReadBundlerFiles(arg0: str, arg1: str) -> tuple[bool, ...]:
    ...
def ReadReconstruction(arg0: str) -> tuple[bool, ...]:
    ...
def ReadStrechaDataset(arg0: str) -> tuple[bool, ...]:
    ...
def WriteBundlerFiles(arg0: ..., arg1: str, arg2: str) -> bool:
    ...
def WriteColmapFiles(arg0: ..., arg1: str) -> bool:
    ...
def WriteNVMFile(arg0: str, arg1: ...) -> bool:
    ...
def WriteNerfStudio(arg0: str, arg1: ..., arg2: typing.SupportsInt, arg3: str) -> bool:
    ...
def WritePlyFile(arg0: str, arg1: ..., arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[3, 1]"], arg3: typing.SupportsInt) -> bool:
    ...
def WriteReconstruction(arg0: ..., arg1: str) -> bool:
    ...
def WriteReconstructionJson(arg0: ..., arg1: str) -> bool:
    ...
def WriteSdfStudio(arg0: str, arg1: ..., arg2: tuple[typing.SupportsFloat, typing.SupportsFloat], arg3: typing.SupportsFloat) -> bool:
    ...
