from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['RandomNumberGenerator', 'RansacParameters', 'RansacSummary']
class RandomNumberGenerator:
    def RandDouble(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> float:
        ...
    def RandFloat(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> float:
        ...
    def RandGaussian(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> float:
        ...
    def RandInt(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> int:
        ...
    def Seed(self, arg0: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt) -> None:
        ...
class RansacParameters:
    use_Tdd_test: bool
    use_lo: bool
    use_mle: bool
    def __init__(self) -> None:
        ...
    @property
    def error_thresh(self) -> float:
        ...
    @error_thresh.setter
    def error_thresh(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def failure_probability(self) -> float:
        ...
    @failure_probability.setter
    def failure_probability(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def lo_start_iterations(self) -> int:
        ...
    @lo_start_iterations.setter
    def lo_start_iterations(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_iterations(self) -> int:
        ...
    @max_iterations.setter
    def max_iterations(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def min_inlier_ratio(self) -> float:
        ...
    @min_inlier_ratio.setter
    def min_inlier_ratio(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def min_iterations(self) -> int:
        ...
    @min_iterations.setter
    def min_iterations(self, arg0: typing.SupportsInt) -> None:
        ...
class RansacSummary:
    @property
    def confidence(self) -> float:
        ...
    @confidence.setter
    def confidence(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def inliers(self) -> list[int]:
        ...
    @inliers.setter
    def inliers(self, arg0: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    @property
    def num_input_data_points(self) -> int:
        ...
    @num_input_data_points.setter
    def num_input_data_points(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_iterations(self) -> int:
        ...
    @num_iterations.setter
    def num_iterations(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_lo_iterations(self) -> int:
        ...
    @num_lo_iterations.setter
    def num_lo_iterations(self, arg0: typing.SupportsInt) -> None:
        ...
