from __future__ import annotations
__all__: list[str] = ['RandomNumberGenerator', 'RansacParameters', 'RansacSummary']
class RandomNumberGenerator:
    @staticmethod
    def RandDouble(*args, **kwargs):
        ...
    @staticmethod
    def RandFloat(*args, **kwargs):
        ...
    @staticmethod
    def RandGaussian(*args, **kwargs):
        ...
    @staticmethod
    def RandInt(*args, **kwargs):
        ...
    @staticmethod
    def Seed(*args, **kwargs):
        ...
    @staticmethod
    def __init__(*args, **kwargs):
        ...
class RansacParameters:
    @staticmethod
    def __init__(*args, **kwargs):
        ...
    @property
    def error_thresh(*args, **kwargs):
        ...
    @error_thresh.setter
    def error_thresh(*args, **kwargs):
        ...
    @property
    def failure_probability(*args, **kwargs):
        ...
    @failure_probability.setter
    def failure_probability(*args, **kwargs):
        ...
    @property
    def lo_start_iterations(*args, **kwargs):
        ...
    @lo_start_iterations.setter
    def lo_start_iterations(*args, **kwargs):
        ...
    @property
    def max_iterations(*args, **kwargs):
        ...
    @max_iterations.setter
    def max_iterations(*args, **kwargs):
        ...
    @property
    def min_inlier_ratio(*args, **kwargs):
        ...
    @min_inlier_ratio.setter
    def min_inlier_ratio(*args, **kwargs):
        ...
    @property
    def min_iterations(*args, **kwargs):
        ...
    @min_iterations.setter
    def min_iterations(*args, **kwargs):
        ...
    @property
    def use_Tdd_test(*args, **kwargs):
        ...
    @use_Tdd_test.setter
    def use_Tdd_test(*args, **kwargs):
        ...
    @property
    def use_lo(*args, **kwargs):
        ...
    @use_lo.setter
    def use_lo(*args, **kwargs):
        ...
    @property
    def use_mle(*args, **kwargs):
        ...
    @use_mle.setter
    def use_mle(*args, **kwargs):
        ...
class RansacSummary:
    @property
    def confidence(*args, **kwargs):
        ...
    @confidence.setter
    def confidence(*args, **kwargs):
        ...
    @property
    def inliers(*args, **kwargs):
        ...
    @inliers.setter
    def inliers(*args, **kwargs):
        ...
    @property
    def num_input_data_points(*args, **kwargs):
        ...
    @num_input_data_points.setter
    def num_input_data_points(*args, **kwargs):
        ...
    @property
    def num_iterations(*args, **kwargs):
        ...
    @num_iterations.setter
    def num_iterations(*args, **kwargs):
        ...
    @property
    def num_lo_iterations(*args, **kwargs):
        ...
    @num_lo_iterations.setter
    def num_lo_iterations(*args, **kwargs):
        ...
